export const COLLABORATOR_LIST_REQUEST = "COLLABORATOR_LIST_REQUEST";
export const COLLABORATOR_LIST_SUCCESS = "COLLABORATOR_LIST_SUCCESS";
export const COLLABORATOR_LIST_FAIL = "COLLABORATOR_LIST_FAIL";

export const COLLABORATOR_DETAILS_REQUEST = "COLLABORATOR_DETAILS_REQUEST";
export const COLLABORATOR_DETAILS_SUCCESS = "COLLABORATOR_DETAILS_SUCCESS";
export const COLLABORATOR_DETAILS_FAIL = "COLLABORATOR_DETAILS_FAIL";

export const COLLABORATOR_DELETE_REQUEST = "COLLABORATOR_DELETE_REQUEST";
export const COLLABORATOR_DELETE_SUCCESS = "COLLABORATOR_DELETE_SUCCESS";
export const COLLABORATOR_DELETE_FAIL = "COLLABORATOR_DELETE_FAIL";

export const COLLABORATOR_CREATE_REQUEST = "COLLABORATOR_CREATE_REQUEST";
export const COLLABORATOR_CREATE_SUCCESS = "COLLABORATOR_CREATE_SUCCESS";
export const COLLABORATOR_CREATE_FAIL = "COLLABORATOR_CREATE_FAIL";
export const COLLABORATOR_CREATE_RESET = "COLLABORATOR_CREATE_RESET";
