export const SUPERSTARDONAR_LIST_REQUEST = "SUPERSTARDONAR_LIST_REQUEST";
export const SUPERSTARDONAR_LIST_SUCCESS = "SUPERSTARDONAR_LIST_SUCCESS";
export const SUPERSTARDONAR_LIST_FAIL = "SUPERSTARDONAR_LIST_FAIL";

export const SUPERSTARDONAR_DETAILS_REQUEST = "SUPERSTARDONAR_DETAILS_REQUEST";
export const SUPERSTARDONAR_DETAILS_SUCCESS = "SUPERSTARDONAR_DETAILS_SUCCESS";
export const SUPERSTARDONAR_DETAILS_FAIL = "SUPERSTARDONAR_DETAILS_FAIL";

export const SUPERSTARDONAR_DELETE_REQUEST = "SUPERSTARDONAR_DELETE_REQUEST";
export const SUPERSTARDONAR_DELETE_SUCCESS = "SUPERSTARDONAR_DELETE_SUCCESS";
export const SUPERSTARDONAR_DELETE_FAIL = "SUPERSTARDONAR_DELETE_FAIL";

export const SUPERSTARDONAR_CREATE_REQUEST = "SUPERSTARDONAR_CREATE_REQUEST";
export const SUPERSTARDONAR_CREATE_SUCCESS = "SUPERSTARDONAR_CREATE_SUCCESS";
export const SUPERSTARDONAR_CREATE_FAIL = "SUPERSTARDONAR_CREATE_FAIL";
export const SUPERSTARDONAR_CREATE_RESET = "SUPERSTARDONAR_CREATE_RESET";

export const SUPERSTARDONAR_UPDATE_REQUEST = "SUPERSTARDONAR_UPDATE_REQUEST";
export const SUPERSTARDONAR_UPDATE_SUCCESS = "SUPERSTARDONAR_UPDATE_SUCCESS";
export const SUPERSTARDONAR_UPDATE_FAIL = "SUPERSTARDONAR_UPDATE_FAIL";
export const SUPERSTARDONAR_UPDATE_RESET = "SUPERSTARDONAR_UPDATE_RESET";
